const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const appsDir = path.resolve(__dirname, '..', 'apps');
const outputPath = path.resolve(__dirname, '..', 'src', 'apps.generated.ts');

const apps = fs
  .readdirSync(appsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .filter((folder) => !folder.startsWith('_'))          // _ prefix = template/hidden, skip
  .filter((folder) => fs.existsSync(path.join(appsDir, folder, 'config.yaml')))
  .map((folder) => {
    const raw = fs.readFileSync(path.join(appsDir, folder, 'config.yaml'), 'utf8');
    const config = yaml.load(raw);
    return {
      folder,
      ...config,
      status: config.status ?? 'live',
      url: config.url ?? `/${folder}`,
    };
  });

const output = `// Auto-generated by scripts/generate-apps.js — do not edit manually
import type { AppConfig } from './types';

const apps: AppConfig[] = ${JSON.stringify(apps, null, 2)};

export default apps;
`;

fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Generated apps.generated.ts with ${apps.length} app(s)`);
