// Auto-generated by scripts/generate-apps.js — do not edit manually
import type { AppConfig } from './types';

const apps: AppConfig[] = [
  {
    "folder": "quarterback",
    "name": "Quarterback Dashboard",
    "description": "Manage Vantage requests end-to-end — assign tickets track team capacity block staffing and PTO and let AI recommend optimal assignments.",
    "icon": "🏈",
    "accent": "#3b82f6",
    "tag": "Admin",
    "author": "Michael Leyh",
    "status": "live",
    "url": "/quarterback"
  },
  {
    "folder": "rapid-bff",
    "name": "Rapid BFF",
    "description": "Rapid BFF survey experience.",
    "icon": "💚",
    "tag": "BFF",
    "accent": "#3d9b6d",
    "author": "Frank Anderson",
    "status": "live",
    "url": "/rapid-bff"
  },
  {
    "folder": "testing",
    "name": "API Test",
    "description": "Demonstrates platform API routing — ping, echo, and a live Claude call.",
    "icon": "🧪",
    "accent": "#8b5cf6",
    "author": "Frank Anderson",
    "tag": "Dev",
    "status": "live",
    "url": "/testing"
  }
];

export default apps;
